name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Detect and Install
        run: |
          if [ -d "smart-city-main/frontend" ]; then
            echo "DIR=smart-city-main/frontend" >> $GITHUB_ENV
          elif [ -d "frontend" ]; then
            echo "DIR=frontend" >> $GITHUB_ENV
          else
            echo "DIR=." >> $GITHUB_ENV
          fi

      - name: Install
        run: |
          cd ${{ env.DIR }}
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd ${{ env.DIR }}
          npm run build
        env:
          NEXT_PUBLIC_SKIP_LINT: true
          NEXT_PUBLIC_API_URL: https://smart-city-backend.onrender.com

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIR }}/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
